AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template that creates Spot Instances, an EventBridge rule, and an FIS scenario.

Parameters:
  
  SpotTargetCapacity:
    Type: Number
    Default: 2
    Description: 'The number of spot units to request for the Spot Fleet'
  
  SpotBudget:
    Type: String
    Default: 2
    Description: 'The budget in $ for all Spot instances in the Fleet'

  OnDemandTargetCapacity:
    Type: Number
    Default: 1
    Description: 'The number of on-demand units to request for the Spot Fleet'
  
  OnDemandBudget:
    Type: String
    Default: 1
    Description: 'The budget in $ for all OnDemand instances in the Fleet'

  SubnetIds:
    Description: The list of Subnet IDs
    Type: String
    Default: "subnet-0af751c807e1fe2f9,subnet-0f7165dbbf6c2cdc9,subnet-013ee744214df5698"
  
  SubscriptionEmail:
    Type: String
    Description: "The email address to receive notifications from the SNS topic."

Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-07caf09b362be10b8
    eu-west-1:
      HVM64: ami-0dfdc165e7af15242

Resources:

  FISRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: AWSSummit_RoleForFIS
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "fis.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSFaultInjectionSimulatorEC2Access
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess

  SSMInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSSummit_RoleForSSM
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref SSMInstanceRole

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LaunchTemplateForSpotFleet
      LaunchTemplateData:
        ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', 'HVM64']
        InstanceRequirements:
            VCpuCount:
              Min: 1
              Max: 4
            MemoryMiB:
              Min: 4096
              Max: 16384
            InstanceGenerations:
              - current
        TagSpecifications:
          - ResourceType: "instance"
            Tags:
              - Key: "Name"
                Value: "AWSSummitSpotFleetInstance"
              - Key: "Interrupt"
                Value: "Yes"
        IamInstanceProfile: 
          Arn: !GetAtt EC2InstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            cd /var/tmp/
            curl -sO https://raw.githubusercontent.com/PaoloL/aws-ec2-spot-events/main/pollig_imds.py

  EC2SpotFleet:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: arn:aws:iam::983441761380:role/aws-ec2-spot-fleet-tagging-role
        TargetCapacity: !Ref SpotTargetCapacity
        TargetCapacityUnitType: units
        ReplaceUnhealthyInstances: True
        SpotMaintenanceStrategies:
          CapacityRebalance:
              ReplacementStrategy: launch-before-terminate
              TerminationDelay: 300
        Type: maintain
        AllocationStrategy: 'priceCapacityOptimized'
        SpotMaxTotalPrice: !Ref SpotBudget
        OnDemandTargetCapacity: !Ref OnDemandTargetCapacity
        OnDemandAllocationStrategy: lowestPrice
        OnDemandMaxTotalPrice: !Ref OnDemandBudget
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref EC2LaunchTemplate
              Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
        InstanceInterruptionBehavior: 'terminate'
  
  EC2SpotAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: AWSSummitSpotAutoscaling
      CapacityRebalance: True
      VPCZoneIdentifier:
        - subnet-0af751c807e1fe2f9
        - subnet-0f7165dbbf6c2cdc9
        - subnet-013ee744214df5698
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      DesiredCapacityType: units
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandAllocationStrategy: prioritized
          OnDemandBaseCapacity: 2
          OnDemandPercentageAboveBaseCapacity: 50
          SpotAllocationStrategy: price-capacity-optimized
          SpotMaxPrice : "1"
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref EC2LaunchTemplate
            Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: t3.large
            - InstanceType: t3.medium
            - InstanceType: t3.small
      Tags:
        - Key: Name
          Value: AWSSummitSpotAutoscalingGroup
          PropagateAtLaunch: true

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AWSSummit_SpotInstancesEvents
      Subscription:
        - Protocol: email
          Endpoint: !Ref SubscriptionEmail

  SNSPermission:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref SNSTopic

  EBBus: 
      Type: AWS::Events::EventBus
      Properties: 
          Name: "AWSSummit_SpotInstancesEventBus"

  EBRuleInterrupt:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventBridge rule that catch-up an interruption warning"
      EventBusName: default
      EventPattern:
        source:
        - aws.ec2
        detail-type:
        - EC2 Spot Instance Interruption Warning
      Targets:
        - Arn: !Ref SNSTopic
          Id: 'SpotTopicEvents'
        - Arn: !GetAtt SpotLogGroup.Arn
          Id: 'SpotLogEvents'
      State: ENABLED
  
  EBRuleRebalance:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventBridge rule that catch-up an rebalance warning"
      EventBusName: default
      EventPattern:
        source:
        - aws.ec2
        detail-type:
        - EC2 Instance Rebalance Recommendation
      Targets:
        - Arn: !Ref SNSTopic
          Id: 'SpotTopicEvents'
        - Arn: !GetAtt SpotLogGroup.Arn
          Id: 'SpotLogEvents'
      State: ENABLED

  FISLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: '/aws/fis/awssummit-experiments'
      RetentionInDays: 7
  
  SpotLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: '/aws/spot/awssummit-experiments'
      RetentionInDays: 7
  
  

  FISExperimentTemplate:
    Type: 'AWS::FIS::ExperimentTemplate'
    Properties:
      RoleArn: !GetAtt FISRole.Arn
      Description: 'Test EC2 Spot instance interruption notices'
      Actions:
        stopSpotInstances:
          ActionId: 'aws:ec2:send-spot-instance-interruptions'
          Targets:
            SpotInstances: selectOneInstanceByTag
          Parameters:
            durationBeforeInterruption: 'PT5M'
      Targets:
        selectOneInstanceByTag:
          ResourceTags:
            "Name": "AWSSummitSpotInstance"
            "Interrupt": "Yes"
          ResourceType: 'aws:ec2:spot-instance'
          SelectionMode: 'COUNT(1)'
      StopConditions:
        - Source: 'none'
      LogConfiguration:
        CloudWatchLogsConfiguration: 
           LogGroupArn: !GetAtt FISLogGroup.Arn
        LogSchemaVersion: 1
      Tags:
        Project: "AWSSummit24"
        Environment: "Demo"

Outputs:
  SpotFleetRequestId:
    Description: 'The Spot Fleet Request ID'
    Value: !Ref EC2SpotFleet
  EventBridgeInterruptRuleArn:
    Description: 'The Amazon EventBridge rule ARN'
    Value: !GetAtt EBRuleInterrupt.Arn
  EventBridgeRebalanceRuleArn:
    Description: 'The Amazon EventBridge rule ARN'
    Value: !GetAtt EBRuleRebalance.Arn
  FISExperimentTemplateId:
    Description: 'The FIS Experiment Template ID'
    Value: !Ref FISExperimentTemplate
